@startuml Reversi

package model {

    abstract class TurnBaseGame {
    change_player()
    make_move()
    }

    abstract class Rules {
    check_validity_of_move()
    define_winner()
    }

    ReversiGame *-- Rules
    ReversiGame <|-- TurnBaseGame
    ReversiGame *-- Board
    ReversiGame *-- Player

    class ReversiGame {
        board : Board
        player : Enum
        rules : Rules
        change_player()
        make_move()
        rules.check_validity_of_move()
        rules.define_winner()
    }

    class AiPlayer {
        board
        difficulty(int)
        get_board()
        calc_move()
    }

    ReversiGame *-- AiPlayer

    class LogHandler {
        log
        update_log(string)
        save_log(type : txt/dat)
    }
}

package view {
    abstract class View {
    start_message()
    render()
    }

    class BoardConsoleView {
        board
        render_board()
    }



    class ReversiConsoleView {
        start_message()
        display_menu()
        render()
    }

    class ReversiGraphicalUi {
        display_menu()
        display_game()
        render()
    }

    ReversiConsoleView <|-- View
    ReversiGraphicalUi <|-- View
    BoardConsoleView <|-- View


}


package controller {
    abstract class Controller {
    game : Game
    view : View
    start_game()
    }

    class ReversiConsoleController {
        game : ReversiGame
        view : ReversiConsoleView
        board_view : BoardConsoleView
        start_game()
    }
}


ReversiGame *-- LogHandler

class Board {
    size
    board_cells : BoardCells
    create_board()
    update_cell()
    get_cell()
}

Board *-- BoardCells

enum Player {
    first
    second
}

enum BoardCells {
    p1
    p2
    empty
    notAllowed
}

package Exeptions {

    class WrongMoveError{

    }

    class WritingFileError{

    }

    class UnexpectedInputError {

    }
}





ReversiConsoleController <|-- Controller


ReversiConsoleController *-- ReversiConsoleView
ReversiConsoleController *-- BoardConsoleView
BoardConsoleView *-- BoardCells
ReversiConsoleController *-- ReversiGame


@enduml